# Generated by Django 5.1.6 on 2025-03-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
