# Generated by Django 5.1.6 on 2025-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='op_day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
