# Generated by Django 5.1.6 on 2025-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_token_op_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='op_day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
