# Generated by Django 5.1.6 on 2025-03-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_op_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='op_day',
        ),
    ]
