# Generated by Django 5.1.6 on 2025-03-14 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_appointment_op_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
